---
default:
  interruptible: true

variables:
  NODE_VERSION: 22-alpine
  NODE_PACKAGE_MANAGER: pnpm
  SKIP_GIT_HOOKS: '1'

stages:
  - install
  - build
  - container

include:
  - project: devops/pipelines
    ref: node@2.0.0
    file:
      - /node/install.gitlab-ci.yml
      - /node/build.gitlab-ci.yml
      - /node/lint.gitlab-ci.yml

  - project: devops/pipelines
    ref: buildah@2.0.0
    file:
      - /buildah/build.gitlab-ci.yml
      - /buildah/registry-gitlab.gitlab-ci.yml

install:
  stage: install
  extends: .node-install

build:
  stage: build
  extends: .node-build
  needs:
    - install
  artifacts:
    paths:
      - '**/dist/'
      - '.svelte-kit/'
    exclude:
      - 'node_modules*'
      - 'node_modules/**/*'

lint:
  stage: build
  extends: .node-lint
  needs:
    - install
    - build

container:
  stage: container
  extends: .container-build
  needs:
    - build
    - lint
  variables:
    CONTAINER_FILE_NAME: Dockerfile
    CONTAINER_IMAGE_NAME: html
    CONTAINER_IMAGE_TAGS: latest
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
